name: EpicHomes
version: '${project.version}'
main: me.loving11ish.epichomes.EpicHomes
api-version: 1.13
folia-supported: true
load: POSTWORLD
authors: [Loving11ish]
description: A fully featured homes plugin that is resource efficient and simple to use.
softdepend: [ PlaceholderAPI, Multiverse-Core ]

commands:

  home:
    description: This is the main command for the plugin.
    usage: "/home [<home-name>|set|delete|list]"
    aliases:
      - h
      - eh
      - homes
      - epichomes

  homeadmin:
    description: This is the command to access all admin features.
    usage: "/homeadmin [delete|visit|list|reload]"
    permission: epichomes.admin
    aliases:
      - ha

  sethome:
    description: This command lets a player st at home at their current location.
    usage: "/sethome <home-name>"

  delhome:
    description: This command lets a player delete the specified home if it exists.
    usage: "/delhome <home-name>"

  importhomes:
    description: The command used by ops to import homes and player data from the StormerHomes plugin.
    usage: "/importhomes"
    permission: epichomes.command.import
    aliases:
      - ih
      - epicimport
      - ei
      - importhome
      - homeimport

permissions:
  epichomes.maxhomes.group1:
    default: true

  epichomes.*:
    default: op
    children:
      epichomes.admin:
        default: op
        children:
          epichomes.update:
            default: op
          epichomes.maxhomes.*:
            default: op

          epichomes.command.*:
            default: op
            children:
              epichomes.command.deleteothers:
                default: op
              epichomes.command.visitothers:
                default: op
              epichomes.command.listothers:
                default: op
              epichomes.command.reload:
                default: op
              epichomes.command.import:
                default: op

          epichomes.bypass.*:
            default: op
            children:
              epichomes.bypass.cooldown:
                default: op
              epichomes.bypass.movement:
                default: op