name: EpicHomes
version: '${project.version}'
main: me.loving11ish.epichomes.EpicHomes
api-version: 1.13
folia-supported: true
authors: [Loving11ish]
description: A fully featured homes plugin that is resource efficient and simple to use.
commands:
  home:
    description: This is the main command for the plugin.
    usage: "/home [<home-name>|set|delete|list|reload]"
    aliases:
      - h
      - eh
      - homes
      - epichomes

permissions:
  epichomes.maxhomes.group1:
    default: true
  epichomes.*:
    default: op
